### ISSUE TITLE
Website data not updating

### ISSUE THREAD

**Issue by spazm** [supportchef/covid-by-region#18]
Data is stale from Nov 2021

**Comment by spazm** [comment]
We miss you, covidbyregion!

**Comment by sean9keenan** [comment]
It looks like node is [OOMing during the deploy](https://github.com/supportchef/covid-by-region/runs/4515140171?check_suite_focus=true) 😱

**Comment by sean9keenan** [comment]
Fixed! I just bumped the max memory limit on the [node process and crossed my fingers](https://github.com/supportchef/covid-by-region/commit/e7684baea29c5d9d017a417e5e4b73776ddc1583).

Thanks for the report, glad you're still using and enjoying covid-by-region :D

**Comment by spazm** [comment]
Woohoo! Thanks

**Comment by spazm** [comment]
Stopped working again.
