### ISSUE TITLE
Update databases automatically

### ISSUE THREAD

**Issue by ronshapiro** [supportchef/covid-by-region#9]
I imagine the data gets updated every time @sean9keenan does a new push... would be cool if we could make this automatic.

**Comment by ronshapiro** [comment]
Actually, I just saw that @sean9keenan started (finished?) working on a bot to update the data - does it also redeploy the site?

**Comment by sean9keenan** [comment]
It does 😁 

I wrote one Github action which attempts to fetch new data every 3 hours, and another that redeploys the website whenever something is merged into master!

**Comment by sean9keenan** [comment]
Correction - I broke it sometime last night because I didn't want it to throw errors every time it _didn't_ find an update (but it was properly updating!). I just pushed a fix that will hopefully both not throw errors, and update when needed 😅
